# 数据集
dataset-path-train: "/mnt/lustre/sjtu/home/yfw51/Datasets/SegTHOR2019/train"
dataset-path-test: "/mnt/lustre/sjtu/home/yfw51/Datasets/SegTHOR2019/test"
dataset-num-dev-samples: 5 # 将训练集中的多少病人用作开发集
dataset-group: True # 是否将同一病人的图片成组输入

# 数据预处理
# expand：将成组数据展开至batch_size维。
# group_diff：对每组数据求1阶差分，与原数据在channel维上concat。
# group_diff2：对每组数据求1阶和2阶差分，与原数据在channel维上concat。
preprocessing: group_diff2, expand # 会在collate_fn中执行的预处理步骤，以逗号隔开多个步骤会让它们按顺序执行

# 训练
#exp-dir: "exp/train" # 实验目录，通常无需设置该参数，会根据配置文件名生成
optimizer: "adam"
criterion: "ce"
num-epoch: 20
batch-size: 1
learning-rate: 1e-3
accum-grad: 1 # 连续累加多少个batch的梯度再优化
resume: "NONE" # "NONE"表示从头训练

# 模型
num-classes: 5 # 最终分类数
unet-input-height: 512 # UNet的输入尺寸（高度）
unet-input-width: 512 # UNet的输入尺寸（宽度）
unet-input-channels: 3 # UNet的输入尺寸（通道数）
unet-init-channels: 64 # 数据正式进入U形网络前应处理至的通道数
unet-num-layers: 4 # UNet的单边网络层数
unet-bilinear: True # UNet中是否使用双线性插值完成上采样

